Repository WildCodeSchool/orleans-0918-php-labo, pull requests merged in 2018-11, with the labels that each got.

#2 ajout de webpack et correction des .env
  .env
  .gitignore
  assets/.gitignore
  assets/css/app.css
  assets/js/app.js
  composer.json
  composer.lock
  config/bundles.php
  config/packages/assets.yaml
  config/packages/webpack_encore.yaml
  package.json
  symfony.lock
  templates/base.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed by PO

#15 Us23 sprint1 : ajout des Entities et des Relations pour qu'Hélène puisse travailler
  src/Entity/Company.php
  src/Entity/Customer.php
  src/Entity/Reservation.php
  src/Migrations/Version20181123084801.php
  src/Migrations/Version20181123085107.php
  src/Migrations/Version20181123091258.php
  src/Migrations/Version20181123110832.php
  src/Repository/CompanyRepository.php
  src/Repository/CustomerRepository.php
  src/Repository/ReservationRepository.php
Labels: Correction Done

#35 Us home
  assets/css/_general.scss
  assets/css/_home.scss
  assets/css/_variables.scss
  assets/css/app.scss
  assets/images/LABO_2016_exter@Jean_PUYO.jpg
  assets/images/labo_portrait.jpg
  assets/js/app.js
  src/Controller/HomeController.php
  templates/home/index.html.twig
Labels: Reviewed by PO

#61 #60 reparation dev
  assets/css/_admin.scss
  templates/base.html.twig
Labels: Correction Done, Reviewed by PO

#62 Dev to Master
  assets/css/_admin.scss
  assets/css/_general.scss
  assets/css/_home.scss
  assets/css/_variables.scss
  assets/css/app.scss
  assets/images/LABO_2016_exter@Jean_PUYO.jpg
  assets/images/labo_portrait.jpg
  assets/js/app.js
  src/Controller/HomeController.php
  templates/base.html.twig
  templates/home/index.html.twig
Labels: Reviewed by PO

#64 #63 renomage du fichier _admin.html.twig
  templates/admin/_navbar.html.twig
  templates/baseAdmin.html.twig
Labels: Reviewed by PO

#52 Us11/12/12/14/15 sprint1 navbar user
  assets/css/_navbarUser.scss
  assets/css/_variables.scss
  assets/css/app.scss
  assets/js/app.js
  package.json
  src/Controller/HomeController.php
  templates/base.html.twig
  templates/home/_navbar.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed by PO

#68 #67 rectif_position_navbar&correctionSCSS
  assets/css/_admin.scss
  assets/css/_navbarUser.scss
Labels: Reviewed by PO

#75 #74_styleBtn_&_hoverColor
  assets/css/_admin.scss
  assets/css/_general.scss
  assets/css/_home.scss
  assets/css/_navbarUser.scss
  templates/home/index.html.twig
Labels: Reviewed by PO

#77 Dev TO Master
  assets/css/_admin.scss
  assets/css/_general.scss
  assets/css/_home.scss
  assets/css/_navbarUser.scss
  assets/css/_variables.scss
  assets/css/app.scss
  assets/js/app.js
  package.json
  src/Controller/HomeController.php
  templates/admin/_navbar.html.twig
  templates/base.html.twig
  templates/baseAdmin.html.twig
  templates/home/_navbar.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed by PO

#79 Us71 sprint2
  assets/css/_admin.scss
  assets/js/app.js
  src/Controller/StaffController.php
  src/Entity/Reservation.php
  src/Entity/Staff.php
  src/Form/StaffType.php
  src/Migrations/Version20181128160850.php
  src/Migrations/Version20181128163255.php
  src/Repository/StaffRepository.php
  templates/admin/_navbar.html.twig
  templates/staff/_delete_form.html.twig
  templates/staff/_form.html.twig
  templates/staff/edit.html.twig
  templates/staff/index.html.twig
  templates/staff/new.html.twig
  templates/staff/show.html.twig
Labels: Reviewed by PO

#80 Sprint2 us81 admin room
  assets/js/app.js
  src/Controller/RoomController.php
  src/Entity/Room.php
  src/Form/RoomType.php
  src/Migrations/Version20181128165226.php
  src/Repository/RoomRepository.php
  templates/admin/_navbar.html.twig
  templates/room/_delete_form.html.twig
  templates/room/_form.html.twig
  templates/room/edit.html.twig
  templates/room/index.html.twig
  templates/room/new.html.twig
  templates/room/show.html.twig
Labels: Correction Done, Reviewed by PO

#86 Dev to MASTER
  assets/css/_currentReservations.scss
  assets/css/_variables.scss
  assets/css/app.scss
  assets/js/app.js
  composer.lock
  src/Controller/ReservationController.php
  src/Migrations/Version20181123084801.php
  src/Migrations/Version20181123085107.php
  src/Migrations/Version20181123091258.php
  src/Migrations/Version20181123110832.php
  src/Migrations/Version20181127162832.php
  src/Migrations/Version20181128163255.php
  src/Migrations/Version20181130130520.php
  symfony.lock
  templates/reservation/currentReservations.html.twig
Labels: Reviewed by PO
