Repository WildCodeSchool/orleans-0918-php-labo, pull requests merged in 2019-01, with the labels that each got.

#190 Sprint06 us51 display archive reservation table
  src/Controller/ReservationController.php
  src/Entity/Reservation.php
  templates/home/_navbar.html.twig
  templates/reservation/archiveReservations.html.twig
Labels: Reviewed by PO

#195 Messagesfash
  assets/css/_admin.scss
  assets/css/_currentReservations.scss
  assets/css/_general.scss
  assets/css/_home.scss
  assets/css/_navbarUser.scss
  src/Controller/EquipementController.php
  src/Controller/ReservationController.php
  src/Controller/RoomController.php
  src/Controller/StaffController.php
  templates/admin/index.html.twig
  templates/base.html.twig
  templates/baseAdmin.html.twig
  templates/home/_navbar.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  templates/reservation/currentReservations.html.twig
  templates/reservation/index.html.twig
  templates/reservation/new.html.twig
Labels: Reviewed by PO

#197 Dev to Master
  assets/css/_admin.scss
  assets/css/_currentReservations.scss
  assets/css/_general.scss
  assets/css/_home.scss
  assets/css/_navbarUser.scss
  src/Controller/EquipementController.php
  src/Controller/ReservationController.php
  src/Controller/RoomController.php
  src/Controller/StaffController.php
  src/Entity/Reservation.php
  templates/admin/index.html.twig
  templates/base.html.twig
  templates/baseAdmin.html.twig
  templates/home/_navbar.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  templates/reservation/archiveReservations.html.twig
  templates/reservation/currentReservations.html.twig
  templates/reservation/index.html.twig
  templates/reservation/new.html.twig
Labels: Reviewed by PO

#196 Us123 date reservation sprint5
  src/Controller/ReservationController.php
  src/Entity/Reservation.php
  templates/reservation/show.html.twig
Labels: Reviewed by PO

#199 Us88 sprint6 pagination admin
  src/Controller/EquipementController.php
  src/Controller/ReservationController.php
  src/Controller/RoomController.php
  src/Controller/StaffController.php
  templates/equipement/index.html.twig
  templates/room/index.html.twig
  templates/staff/index.html.twig
Labels: Correction Done, Reviewed by PO

#198 Us110 sprint5 modif reservation v2
  assets/css/_form.scss
  src/Controller/ReservationController.php
  templates/reservation/_formEdit.html.twig
  templates/reservation/edit.html.twig
Labels: Conflict, Reviewed by PO

#202 Dev To Master
  assets/css/_form.scss
  src/Controller/EquipementController.php
  src/Controller/ReservationController.php
  src/Controller/RoomController.php
  src/Controller/StaffController.php
  src/Entity/Reservation.php
  templates/equipement/index.html.twig
  templates/reservation/_formEdit.html.twig
  templates/reservation/edit.html.twig
  templates/reservation/show.html.twig
  templates/room/index.html.twig
  templates/staff/index.html.twig
Labels: Reviewed by PO

#208 Sprint7 us141 remove delete button
  templates/equipement/index.html.twig
  templates/room/index.html.twig
  templates/staff/index.html.twig
Labels: Reviewed by PO

#209 Sprint7 us142 modification button
  templates/equipement/_form.html.twig
  templates/room/_form.html.twig
  templates/room/edit.html.twig
  templates/staff/_form.html.twig
  templates/staff/edit.html.twig
Labels: Reviewed by PO

#207 Sprint7 us149 pagination comments
  assets/css/_currentReservations.scss
  config/packages/knp_paginator.yaml
  config/services.yaml
  src/Controller/EquipementController.php
  src/Controller/ReservationController.php
  src/Controller/RoomController.php
  src/Controller/StaffController.php
  templates/reservation/archiveReservations.html.twig
  templates/reservation/currentReservations.html.twig
Labels: Reviewed by PO

#210 ajout de la liste des équipements et de la signature dans la vue déta…
  assets/css/_detailReservation.scss
  src/Controller/ReservationController.php
  src/Service/SignatureService.php
  templates/reservation/show.html.twig
Labels: Reviewed by PO

#213 style mise en place
  assets/css/_currentReservations.scss
  assets/css/_form.scss
  templates/equipement/edit.html.twig
  templates/equipement/index.html.twig
  templates/reservation/show.html.twig
  templates/room/index.html.twig
  templates/staff/edit.html.twig
  templates/staff/index.html.twig
Labels: Reviewed by PO

#214 Sprint7 us143 champs non modifiables
  assets/css/_form.scss
  src/Controller/ReservationController.php
  templates/reservation/_formEdit.html.twig
  templates/reservation/edit.html.twig
Labels: Reviewed by PO

#215 Sprint06 us42 action btn archive
  assets/css/_currentReservations.scss
  assets/js/archive.js
  src/Controller/ReservationController.php
  src/Entity/Reservation.php
  src/Form/ArchiveType.php
  templates/reservation/_archiveForm.html.twig
  templates/reservation/currentReservations.html.twig
  webpack.config.js
Labels: Reviewed by PO

#235 Sprint7 validate signature
  .env
  .gitignore
  assets/css/_form.scss
  config/services.yaml
  src/Controller/ReservationController.php
  src/Form/ReservationType.php
  src/Service/SignatureService.php
  templates/reservation/_form.html.twig
Labels: Reviewed by PO

#234 Sprint07 us50 set end date time
  src/Controller/ReservationController.php
  src/Entity/Reservation.php
Labels: Reviewed by PO

#240 correctif sur la navbar suite entretien client
  assets/css/_admin.scss
Labels: Reviewed by PO

#242 suppression des fichiers et routes inutiles, mise à jour des controll…
  src/Controller/AdminController.php
  src/Controller/EquipementController.php
  src/Controller/ReservationController.php
  src/Controller/RoomController.php
  src/Controller/StaffController.php
  templates/admin/index.html.twig
  templates/equipement/_delete_form.html.twig
  templates/reservation/_delete_form.html.twig
  templates/reservation/index.html.twig
  templates/room/_delete_form.html.twig
  templates/staff/_delete_form.html.twig
  templates/staff/index.html.twig
  templates/staff/show.html.twig
Labels: Reviewed by PO

#246 Dev to Master
  .env
  .gitignore
  assets/css/_admin.scss
  assets/css/_currentReservations.scss
  assets/css/_form.scss
  assets/js/archive.js
  config/services.yaml
  src/Controller/AdminController.php
  src/Controller/EquipementController.php
  src/Controller/ReservationController.php
  src/Controller/RoomController.php
  src/Controller/StaffController.php
  src/Entity/Reservation.php
  src/Form/ArchiveType.php
  src/Form/ReservationType.php
  src/Service/SignatureService.php
  templates/admin/index.html.twig
  templates/equipement/_delete_form.html.twig
  templates/equipement/edit.html.twig
  templates/equipement/index.html.twig
  templates/reservation/_archiveForm.html.twig
  templates/reservation/_delete_form.html.twig
  templates/reservation/_form.html.twig
  templates/reservation/_formEdit.html.twig
  templates/reservation/archiveReservations.html.twig
  templates/reservation/currentReservations.html.twig
  templates/reservation/edit.html.twig
  templates/reservation/index.html.twig
  templates/reservation/new.html.twig
  templates/reservation/show.html.twig
  templates/room/_delete_form.html.twig
  templates/room/index.html.twig
  templates/room/new.html.twig
  templates/staff/_delete_form.html.twig
  templates/staff/edit.html.twig
  templates/staff/index.html.twig
  templates/staff/new.html.twig
  templates/staff/show.html.twig
  webpack.config.js
Labels: Reviewed by PO

#243 Us152 archivereservation detail
  src/Controller/ReservationController.php
  templates/reservation/archiveReservations.html.twig
  templates/reservation/archiveshow.html.twig
Labels: Reviewed by PO

#244 Sprint7 us160 bouton reserver
  assets/css/_home.scss
  templates/home/index.html.twig
Labels: Reviewed by PO

#248 Us140 sprint7 admin staff button is activ
  assets/css/_form.scss
  src/Controller/StaffController.php
  src/Entity/Staff.php
  src/Form/EnableDisableStaffType.php
  src/Form/ReservationType.php
  templates/staff/_enableDisableStaffForm.html.twig
  templates/staff/index.html.twig
Labels: Reviewed by PO

#249 Us153 cleaningarchive
  assets/js/cleaningArchive.js
  src/Controller/ReservationController.php
  src/Entity/Reservation.php
  src/Form/CleaningArchiveType.php
  src/Repository/ReservationRepository.php
  templates/reservation/_cleanArchiveForm.html.twig
  templates/reservation/archiveReservations.html.twig
  webpack.config.js
Labels: Reviewed by PO

#247 Nettoyage phpdoc
  src/Controller/EquipementController.php
  src/Controller/HomeController.php
  src/Controller/ReservationController.php
  src/Controller/RoomController.php
  src/Controller/StaffController.php
  src/Form/ArchiveType.php
  src/Form/CompanyType.php
  src/Form/CustomerType.php
  src/Form/EquipementType.php
  src/Form/ReservationEquipementType.php
  src/Form/ReservationType.php
  src/Form/RoomType.php
  src/Form/StaffType.php
  src/Service/SignatureService.php
Labels: Reviewed by PO

#255 Ajout du fichier SQL, ajout du fichier migration propre et correctio…
  BDD.sql
  src/Controller/ReservationController.php
  src/DataFixtures/AppFixtures.php
  src/Entity/Staff.php
  src/Migrations/Version20190110165825.php
Labels: Reviewed by PO

#256 Sprint7 base64 signature generator
  assets/css/_general.scss
  public/emptysignature.png
  public/signature.php
Labels: Reviewed by PO

#261 Rajout du fichier SQL et de la migration propres envoyés au client pour compléter le Github
  BDD.sql
  src/Migrations/Version20190110165825.php
Labels: Reviewed by PO

#263 Correction bug
  assets/css/_form.scss
  assets/js/signature.js
  templates/layout.html.twig
  templates/reservation/_form.html.twig
  templates/reservation/show.html.twig
Labels: Reviewed by PO

#265 Fix modif resa
  assets/css/_form.scss
Labels: Reviewed by PO

#267 Package apache
  composer.json
  composer.lock
  public/.htaccess
  symfony.lock
Labels: Reviewed by PO

#269 Fix archives
  src/Repository/ReservationRepository.php
Labels: Reviewed by PO
